name: duckdb_dart
description: A DuckDB client for Dart  
version: 0.3.0
repository: https://github.com/thumbert/duckdb_dart

environment:
  sdk: ^3.3.4

platforms:
  linux:
  macos:
  windows:

dependencies:
  ffi: ^2.1.3

dev_dependencies:
  ffigen: ^12.0.0
  lints: ^4.0.0
  test: ^1.24.0

topics:
  - sql
  - database
  - ffi 