name: duckdb_dart
description: A DuckDb client for Dart  
version: 0.2.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  ffigen: ^12.0.0
  lints: ^3.0.0
  test: ^1.24.0

