name: duckdb_dart
description: A DuckDB client for Dart  
version: 0.3.9
repository: https://github.com/thumbert/duckdb_dart

environment:
  sdk: ^3.3.4

platforms:
  linux:
  macos:
  windows:

dependencies:
  decimal: ^3.0.0
  ffi: ^2.1.3

dev_dependencies:
  ffigen: ^16.0.0
  lints: ^5.1.0
  test: ^1.24.0

topics:
  - sql
  - database
  - ffi 